name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }} # Exibe o nome do usuário e o número da execução
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
